// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: billing.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addAddonCardsToQuota = `-- name: AddAddonCardsToQuota :execrows
update usage_quotas uq
set cards_limit = uq.cards_limit + $1,
    updated_at  = now()
where uq.id = (
    select sub.id
    from usage_quotas sub
    where sub.user_id = $2
      and sub.period_start <= $3
      and sub.period_end > $3
    order by sub.period_start desc
    limit 1
)
`

type AddAddonCardsToQuotaParams struct {
	ExtraCards int32
	UserID     uuid.UUID
	NowAt      pgtype.Timestamptz
}

// Увеличивает лимит карточек в текущей квоте пользователя после покупки addon.
// Подзапрос нужен, потому что PostgreSQL не поддерживает ORDER BY/LIMIT в UPDATE напрямую.
func (q *Queries) AddAddonCardsToQuota(ctx context.Context, arg AddAddonCardsToQuotaParams) (int64, error) {
	result, err := q.db.Exec(ctx, addAddonCardsToQuota, arg.ExtraCards, arg.UserID, arg.NowAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countGeneratedCardsForUserInPeriod = `-- name: CountGeneratedCardsForUserInPeriod :one
select count(*)
from generated_cards gc
join generations g on g.id = gc.generation_id
where g.user_id = $1
  and g.status = 'completed'
  and gc.created_at >= $2
  and gc.created_at < $3
`

type CountGeneratedCardsForUserInPeriodParams struct {
	UserID      uuid.UUID
	PeriodStart pgtype.Timestamptz
	PeriodEnd   pgtype.Timestamptz
}

// Считаем готовые карточки по факту из generated_cards, чтобы billing-экран не зависел от фоновой синхронизации usage_quotas.
func (q *Queries) CountGeneratedCardsForUserInPeriod(ctx context.Context, arg CountGeneratedCardsForUserInPeriodParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGeneratedCardsForUserInPeriod, arg.UserID, arg.PeriodStart, arg.PeriodEnd)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :one
insert into payments (
    user_id,
    subscription_id,
    addon_product_id,
    provider,
    provider_payment_id,
    kind,
    status,
    amount,
    currency,
    checkout_url
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
returning id, user_id, subscription_id, addon_product_id, provider, provider_payment_id, kind, status, amount, currency, checkout_url, paid_at, created_at
`

type CreatePaymentParams struct {
	UserID            uuid.UUID
	SubscriptionID    pgtype.UUID
	AddonProductID    pgtype.UUID
	Provider          string
	ProviderPaymentID pgtype.Text
	Kind              string
	Status            string
	Amount            int32
	Currency          string
	CheckoutUrl       pgtype.Text
}

// Создаём запись платежа после получения checkout от провайдера.
func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.UserID,
		arg.SubscriptionID,
		arg.AddonProductID,
		arg.Provider,
		arg.ProviderPaymentID,
		arg.Kind,
		arg.Status,
		arg.Amount,
		arg.Currency,
		arg.CheckoutUrl,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionID,
		&i.AddonProductID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Kind,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.CheckoutUrl,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
insert into subscriptions (
    user_id,
    plan_id,
    status,
    provider,
    has_payment_method,
    started_at,
    current_period_start,
    current_period_end,
    renews_at,
    cancels_at
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
returning id, user_id, plan_id, status, provider, provider_subscription_id, has_payment_method, started_at, current_period_start, current_period_end, renews_at, cancels_at, ended_at, created_at, updated_at
`

type CreateSubscriptionParams struct {
	UserID             uuid.UUID
	PlanID             uuid.UUID
	Status             string
	Provider           string
	HasPaymentMethod   bool
	StartedAt          pgtype.Timestamptz
	CurrentPeriodStart pgtype.Timestamptz
	CurrentPeriodEnd   pgtype.Timestamptz
	RenewsAt           pgtype.Timestamptz
	CancelsAt          pgtype.Timestamptz
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.UserID,
		arg.PlanID,
		arg.Status,
		arg.Provider,
		arg.HasPaymentMethod,
		arg.StartedAt,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.RenewsAt,
		arg.CancelsAt,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.Provider,
		&i.ProviderSubscriptionID,
		&i.HasPaymentMethod,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.RenewsAt,
		&i.CancelsAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUsageQuota = `-- name: CreateUsageQuota :one
insert into usage_quotas (
    user_id,
    subscription_id,
    period_start,
    period_end,
    cards_limit,
    cards_used
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
returning id, user_id, subscription_id, period_start, period_end, cards_limit, cards_used, created_at, updated_at
`

type CreateUsageQuotaParams struct {
	UserID         uuid.UUID
	SubscriptionID uuid.UUID
	PeriodStart    pgtype.Timestamptz
	PeriodEnd      pgtype.Timestamptz
	CardsLimit     int32
	CardsUsed      int32
}

func (q *Queries) CreateUsageQuota(ctx context.Context, arg CreateUsageQuotaParams) (UsageQuota, error) {
	row := q.db.QueryRow(ctx, createUsageQuota,
		arg.UserID,
		arg.SubscriptionID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.CardsLimit,
		arg.CardsUsed,
	)
	var i UsageQuota
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.CardsLimit,
		&i.CardsUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAddonProductByCode = `-- name: GetAddonProductByCode :one
select
    id,
    code,
    title,
    description,
    price,
    cards_count,
    is_active,
    created_at,
    updated_at
from addon_products
where code = $1
  and is_active = true
limit 1
`

func (q *Queries) GetAddonProductByCode(ctx context.Context, code string) (AddonProduct, error) {
	row := q.db.QueryRow(ctx, getAddonProductByCode, code)
	var i AddonProduct
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.CardsCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingPlanByCode = `-- name: GetBillingPlanByCode :one
select
    id,
    code,
    name,
    monthly_price,
    yearly_monthly_price,
    cards_per_month,
    is_popular,
    is_active,
    created_at,
    updated_at
from plans
where code = $1
  and is_active = true
limit 1
`

func (q *Queries) GetBillingPlanByCode(ctx context.Context, code string) (Plan, error) {
	row := q.db.QueryRow(ctx, getBillingPlanByCode, code)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.MonthlyPrice,
		&i.YearlyMonthlyPrice,
		&i.CardsPerMonth,
		&i.IsPopular,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentSubscriptionByUserID = `-- name: GetCurrentSubscriptionByUserID :one
select
    s.id,
    s.user_id,
    s.plan_id,
    s.status,
    s.provider,
    s.provider_subscription_id,
    s.has_payment_method,
    s.started_at,
    s.current_period_start,
    s.current_period_end,
    s.renews_at,
    s.cancels_at,
    s.ended_at,
    s.created_at,
    s.updated_at,
    p.code as plan_code,
    p.name as plan_name,
    p.cards_per_month
from subscriptions s
join plans p on p.id = s.plan_id
where s.user_id = $1
  and s.status in ('active', 'scheduled_cancel')
order by s.created_at desc
limit 1
`

type GetCurrentSubscriptionByUserIDRow struct {
	ID                     uuid.UUID
	UserID                 uuid.UUID
	PlanID                 uuid.UUID
	Status                 string
	Provider               string
	ProviderSubscriptionID pgtype.Text
	HasPaymentMethod       bool
	StartedAt              pgtype.Timestamptz
	CurrentPeriodStart     pgtype.Timestamptz
	CurrentPeriodEnd       pgtype.Timestamptz
	RenewsAt               pgtype.Timestamptz
	CancelsAt              pgtype.Timestamptz
	EndedAt                pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	PlanCode               string
	PlanName               string
	CardsPerMonth          int32
}

func (q *Queries) GetCurrentSubscriptionByUserID(ctx context.Context, userID uuid.UUID) (GetCurrentSubscriptionByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getCurrentSubscriptionByUserID, userID)
	var i GetCurrentSubscriptionByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.Provider,
		&i.ProviderSubscriptionID,
		&i.HasPaymentMethod,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.RenewsAt,
		&i.CancelsAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlanCode,
		&i.PlanName,
		&i.CardsPerMonth,
	)
	return i, err
}

const getCurrentUsageQuotaBySubscriptionID = `-- name: GetCurrentUsageQuotaBySubscriptionID :one
select
    id,
    user_id,
    subscription_id,
    period_start,
    period_end,
    cards_limit,
    cards_used,
    created_at,
    updated_at
from usage_quotas
where subscription_id = $1
  and period_start <= $2
  and period_end > $2
order by period_start desc
limit 1
`

type GetCurrentUsageQuotaBySubscriptionIDParams struct {
	SubscriptionID uuid.UUID
	NowAt          pgtype.Timestamptz
}

func (q *Queries) GetCurrentUsageQuotaBySubscriptionID(ctx context.Context, arg GetCurrentUsageQuotaBySubscriptionIDParams) (UsageQuota, error) {
	row := q.db.QueryRow(ctx, getCurrentUsageQuotaBySubscriptionID, arg.SubscriptionID, arg.NowAt)
	var i UsageQuota
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.CardsLimit,
		&i.CardsUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByProviderID = `-- name: GetPaymentByProviderID :one
select
    id,
    user_id,
    subscription_id,
    addon_product_id,
    provider,
    provider_payment_id,
    kind,
    status,
    amount,
    currency,
    checkout_url,
    paid_at,
    created_at
from payments
where provider_payment_id = $1
limit 1
`

// Ищем платёж по внешнему ID провайдера для идемпотентной обработки webhook.
func (q *Queries) GetPaymentByProviderID(ctx context.Context, providerPaymentID pgtype.Text) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByProviderID, providerPaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionID,
		&i.AddonProductID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.Kind,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.CheckoutUrl,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
select
    id,
    user_id,
    plan_id,
    status,
    provider,
    provider_subscription_id,
    has_payment_method,
    started_at,
    current_period_start,
    current_period_end,
    renews_at,
    cancels_at,
    ended_at,
    created_at,
    updated_at
from subscriptions
where id = $1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.Provider,
		&i.ProviderSubscriptionID,
		&i.HasPaymentMethod,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.RenewsAt,
		&i.CancelsAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAddonProducts = `-- name: ListActiveAddonProducts :many
select
    id,
    code,
    title,
    description,
    price,
    cards_count,
    is_active,
    created_at,
    updated_at
from addon_products
where is_active = true
order by cards_count asc, created_at asc
`

func (q *Queries) ListActiveAddonProducts(ctx context.Context) ([]AddonProduct, error) {
	rows, err := q.db.Query(ctx, listActiveAddonProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AddonProduct
	for rows.Next() {
		var i AddonProduct
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.CardsCount,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveBillingPlans = `-- name: ListActiveBillingPlans :many
select
    id,
    code,
    name,
    monthly_price,
    yearly_monthly_price,
    cards_per_month,
    is_popular,
    is_active,
    created_at,
    updated_at
from plans
where is_active = true
order by monthly_price asc, created_at asc
`

func (q *Queries) ListActiveBillingPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listActiveBillingPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.MonthlyPrice,
			&i.YearlyMonthlyPrice,
			&i.CardsPerMonth,
			&i.IsPopular,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsDueForRenewal = `-- name: ListSubscriptionsDueForRenewal :many
select
    s.id,
    s.user_id,
    s.plan_id,
    s.provider,
    s.provider_subscription_id,
    s.current_period_start,
    s.current_period_end,
    s.renews_at,
    p.code as plan_code,
    p.monthly_price,
    p.yearly_monthly_price,
    p.cards_per_month
from subscriptions s
join plans p on p.id = s.plan_id
where s.status = 'active'
  and s.has_payment_method = true
  and s.provider = 'yookassa'
  and s.provider_subscription_id is not null
  and s.renews_at <= $1
  and not exists (
      select 1
      from payments pay
      where pay.subscription_id = s.id
        and pay.kind = 'subscription'
        and pay.status = 'pending'
  )
order by s.renews_at asc
limit $2
`

type ListSubscriptionsDueForRenewalParams struct {
	NowAt      pgtype.Timestamptz
	BatchLimit int32
}

type ListSubscriptionsDueForRenewalRow struct {
	ID                     uuid.UUID
	UserID                 uuid.UUID
	PlanID                 uuid.UUID
	Provider               string
	ProviderSubscriptionID pgtype.Text
	CurrentPeriodStart     pgtype.Timestamptz
	CurrentPeriodEnd       pgtype.Timestamptz
	RenewsAt               pgtype.Timestamptz
	PlanCode               string
	MonthlyPrice           int32
	YearlyMonthlyPrice     pgtype.Int4
	CardsPerMonth          int32
}

// Находим активные подписки, которым пора создать рекуррентный платёж.
// pending-платёж по той же подписке означает, что попытка уже создана и ждёт webhook.
func (q *Queries) ListSubscriptionsDueForRenewal(ctx context.Context, arg ListSubscriptionsDueForRenewalParams) ([]ListSubscriptionsDueForRenewalRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsDueForRenewal, arg.NowAt, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscriptionsDueForRenewalRow
	for rows.Next() {
		var i ListSubscriptionsDueForRenewalRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Provider,
			&i.ProviderSubscriptionID,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.RenewsAt,
			&i.PlanCode,
			&i.MonthlyPrice,
			&i.YearlyMonthlyPrice,
			&i.CardsPerMonth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentCanceled = `-- name: MarkPaymentCanceled :execrows
update payments
set status = 'canceled'
where provider_payment_id = $1
  and status = 'pending'
`

// Помечаем платёж отменённым после webhook payment.canceled.
func (q *Queries) MarkPaymentCanceled(ctx context.Context, providerPaymentID pgtype.Text) (int64, error) {
	result, err := q.db.Exec(ctx, markPaymentCanceled, providerPaymentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPaymentPaid = `-- name: MarkPaymentPaid :execrows
update payments
set status  = 'paid',
    paid_at = $1
where provider_payment_id = $2
  and status = 'pending'
`

type MarkPaymentPaidParams struct {
	PaidAt            pgtype.Timestamptz
	ProviderPaymentID pgtype.Text
}

// Фиксируем успешное завершение платежа после webhook payment.succeeded.
func (q *Queries) MarkPaymentPaid(ctx context.Context, arg MarkPaymentPaidParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPaymentPaid, arg.PaidAt, arg.ProviderPaymentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSubscriptionScheduledCancel = `-- name: MarkSubscriptionScheduledCancel :execrows
update subscriptions
set status = 'scheduled_cancel',
    cancels_at = $1,
    updated_at = now()
where id = $2
  and user_id = $3
  and status = 'active'
`

type MarkSubscriptionScheduledCancelParams struct {
	CancelsAt pgtype.Timestamptz
	ID        uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) MarkSubscriptionScheduledCancel(ctx context.Context, arg MarkSubscriptionScheduledCancelParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSubscriptionScheduledCancel, arg.CancelsAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sumReservedGenerationCardsForUserInPeriod = `-- name: SumReservedGenerationCardsForUserInPeriod :one
select coalesce(sum(card_count), 0)::bigint
from generations
where user_id = $1
  and status in ('queued', 'processing', 'completed')
  and created_at >= $2
  and created_at < $3
`

type SumReservedGenerationCardsForUserInPeriodParams struct {
	UserID      uuid.UUID
	PeriodStart pgtype.Timestamptz
	PeriodEnd   pgtype.Timestamptz
}

// Для проверки лимита учитываем уже созданные generation, которые ещё не завершились ошибкой.
// Так пользователь не сможет переполнить квоту пачкой параллельных запусков.
func (q *Queries) SumReservedGenerationCardsForUserInPeriod(ctx context.Context, arg SumReservedGenerationCardsForUserInPeriodParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumReservedGenerationCardsForUserInPeriod, arg.UserID, arg.PeriodStart, arg.PeriodEnd)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertActiveSubscription = `-- name: UpsertActiveSubscription :one
insert into subscriptions (
    user_id,
    plan_id,
    status,
    provider,
    provider_subscription_id,
    has_payment_method,
    started_at,
    current_period_start,
    current_period_end,
    renews_at,
    cancels_at
) values (
    $1,
    $2,
    'active',
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    null
)
on conflict (user_id) where status in ('active', 'scheduled_cancel')
do update set
    plan_id                  = excluded.plan_id,
    status                   = 'active',
    provider                 = excluded.provider,
    provider_subscription_id = excluded.provider_subscription_id,
    has_payment_method       = excluded.has_payment_method,
    current_period_start     = excluded.current_period_start,
    current_period_end       = excluded.current_period_end,
    renews_at                = excluded.renews_at,
    cancels_at               = null,
    updated_at               = now()
returning id, user_id, plan_id, status, provider, provider_subscription_id, has_payment_method, started_at, current_period_start, current_period_end, renews_at, cancels_at, ended_at, created_at, updated_at
`

type UpsertActiveSubscriptionParams struct {
	UserID                 uuid.UUID
	PlanID                 uuid.UUID
	Provider               string
	ProviderSubscriptionID pgtype.Text
	HasPaymentMethod       bool
	StartedAt              pgtype.Timestamptz
	CurrentPeriodStart     pgtype.Timestamptz
	CurrentPeriodEnd       pgtype.Timestamptz
	RenewsAt               pgtype.Timestamptz
}

// Создаёт или обновляет активную подписку после успешного платежа.
// ON CONFLICT по user_id гарантирует, что у пользователя всегда одна активная запись.
func (q *Queries) UpsertActiveSubscription(ctx context.Context, arg UpsertActiveSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, upsertActiveSubscription,
		arg.UserID,
		arg.PlanID,
		arg.Provider,
		arg.ProviderSubscriptionID,
		arg.HasPaymentMethod,
		arg.StartedAt,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.RenewsAt,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.Provider,
		&i.ProviderSubscriptionID,
		&i.HasPaymentMethod,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.RenewsAt,
		&i.CancelsAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUsageQuotaForSubscription = `-- name: UpsertUsageQuotaForSubscription :one
insert into usage_quotas (
    user_id,
    subscription_id,
    period_start,
    period_end,
    cards_limit,
    cards_used
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    0
)
on conflict (subscription_id, period_start, period_end)
do update set
    cards_limit = excluded.cards_limit,
    updated_at  = now()
returning id, user_id, subscription_id, period_start, period_end, cards_limit, cards_used, created_at, updated_at
`

type UpsertUsageQuotaForSubscriptionParams struct {
	UserID         uuid.UUID
	SubscriptionID uuid.UUID
	PeriodStart    pgtype.Timestamptz
	PeriodEnd      pgtype.Timestamptz
	CardsLimit     int32
}

// Создаёт или сбрасывает usage_quota при начале нового billing-периода.
func (q *Queries) UpsertUsageQuotaForSubscription(ctx context.Context, arg UpsertUsageQuotaForSubscriptionParams) (UsageQuota, error) {
	row := q.db.QueryRow(ctx, upsertUsageQuotaForSubscription,
		arg.UserID,
		arg.SubscriptionID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.CardsLimit,
	)
	var i UsageQuota
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.CardsLimit,
		&i.CardsUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
