// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: billing.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countGeneratedCardsForUserInPeriod = `-- name: CountGeneratedCardsForUserInPeriod :one
select count(*)
from generated_cards gc
join generations g on g.id = gc.generation_id
where g.user_id = $1
  and g.status = 'completed'
  and gc.created_at >= $2
  and gc.created_at < $3
`

type CountGeneratedCardsForUserInPeriodParams struct {
	UserID      uuid.UUID
	PeriodStart pgtype.Timestamptz
	PeriodEnd   pgtype.Timestamptz
}

// Считаем готовые карточки по факту из generated_cards, чтобы billing-экран не зависел от фоновой синхронизации usage_quotas.
func (q *Queries) CountGeneratedCardsForUserInPeriod(ctx context.Context, arg CountGeneratedCardsForUserInPeriodParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGeneratedCardsForUserInPeriod, arg.UserID, arg.PeriodStart, arg.PeriodEnd)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubscription = `-- name: CreateSubscription :one
insert into subscriptions (
    user_id,
    plan_id,
    status,
    provider,
    has_payment_method,
    started_at,
    current_period_start,
    current_period_end,
    renews_at,
    cancels_at
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
returning id, user_id, plan_id, status, provider, provider_subscription_id, has_payment_method, started_at, current_period_start, current_period_end, renews_at, cancels_at, ended_at, created_at, updated_at
`

type CreateSubscriptionParams struct {
	UserID             uuid.UUID
	PlanID             uuid.UUID
	Status             string
	Provider           string
	HasPaymentMethod   bool
	StartedAt          pgtype.Timestamptz
	CurrentPeriodStart pgtype.Timestamptz
	CurrentPeriodEnd   pgtype.Timestamptz
	RenewsAt           pgtype.Timestamptz
	CancelsAt          pgtype.Timestamptz
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.UserID,
		arg.PlanID,
		arg.Status,
		arg.Provider,
		arg.HasPaymentMethod,
		arg.StartedAt,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.RenewsAt,
		arg.CancelsAt,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.Provider,
		&i.ProviderSubscriptionID,
		&i.HasPaymentMethod,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.RenewsAt,
		&i.CancelsAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUsageQuota = `-- name: CreateUsageQuota :one
insert into usage_quotas (
    user_id,
    subscription_id,
    period_start,
    period_end,
    cards_limit,
    cards_used
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
returning id, user_id, subscription_id, period_start, period_end, cards_limit, cards_used, created_at, updated_at
`

type CreateUsageQuotaParams struct {
	UserID         uuid.UUID
	SubscriptionID uuid.UUID
	PeriodStart    pgtype.Timestamptz
	PeriodEnd      pgtype.Timestamptz
	CardsLimit     int32
	CardsUsed      int32
}

func (q *Queries) CreateUsageQuota(ctx context.Context, arg CreateUsageQuotaParams) (UsageQuota, error) {
	row := q.db.QueryRow(ctx, createUsageQuota,
		arg.UserID,
		arg.SubscriptionID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.CardsLimit,
		arg.CardsUsed,
	)
	var i UsageQuota
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.CardsLimit,
		&i.CardsUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAddonProductByCode = `-- name: GetAddonProductByCode :one
select
    id,
    code,
    title,
    description,
    price,
    cards_count,
    is_active,
    created_at,
    updated_at
from addon_products
where code = $1
  and is_active = true
limit 1
`

func (q *Queries) GetAddonProductByCode(ctx context.Context, code string) (AddonProduct, error) {
	row := q.db.QueryRow(ctx, getAddonProductByCode, code)
	var i AddonProduct
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.CardsCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingPlanByCode = `-- name: GetBillingPlanByCode :one
select
    id,
    code,
    name,
    monthly_price,
    yearly_monthly_price,
    cards_per_month,
    is_popular,
    is_active,
    created_at,
    updated_at
from plans
where code = $1
  and is_active = true
limit 1
`

func (q *Queries) GetBillingPlanByCode(ctx context.Context, code string) (Plan, error) {
	row := q.db.QueryRow(ctx, getBillingPlanByCode, code)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.MonthlyPrice,
		&i.YearlyMonthlyPrice,
		&i.CardsPerMonth,
		&i.IsPopular,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentSubscriptionByUserID = `-- name: GetCurrentSubscriptionByUserID :one
select
    s.id,
    s.user_id,
    s.plan_id,
    s.status,
    s.provider,
    s.provider_subscription_id,
    s.has_payment_method,
    s.started_at,
    s.current_period_start,
    s.current_period_end,
    s.renews_at,
    s.cancels_at,
    s.ended_at,
    s.created_at,
    s.updated_at,
    p.code as plan_code,
    p.name as plan_name,
    p.cards_per_month
from subscriptions s
join plans p on p.id = s.plan_id
where s.user_id = $1
  and s.status in ('active', 'scheduled_cancel')
order by s.created_at desc
limit 1
`

type GetCurrentSubscriptionByUserIDRow struct {
	ID                     uuid.UUID
	UserID                 uuid.UUID
	PlanID                 uuid.UUID
	Status                 string
	Provider               string
	ProviderSubscriptionID pgtype.Text
	HasPaymentMethod       bool
	StartedAt              pgtype.Timestamptz
	CurrentPeriodStart     pgtype.Timestamptz
	CurrentPeriodEnd       pgtype.Timestamptz
	RenewsAt               pgtype.Timestamptz
	CancelsAt              pgtype.Timestamptz
	EndedAt                pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	PlanCode               string
	PlanName               string
	CardsPerMonth          int32
}

func (q *Queries) GetCurrentSubscriptionByUserID(ctx context.Context, userID uuid.UUID) (GetCurrentSubscriptionByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getCurrentSubscriptionByUserID, userID)
	var i GetCurrentSubscriptionByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.Provider,
		&i.ProviderSubscriptionID,
		&i.HasPaymentMethod,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.RenewsAt,
		&i.CancelsAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlanCode,
		&i.PlanName,
		&i.CardsPerMonth,
	)
	return i, err
}

const getCurrentUsageQuotaBySubscriptionID = `-- name: GetCurrentUsageQuotaBySubscriptionID :one
select
    id,
    user_id,
    subscription_id,
    period_start,
    period_end,
    cards_limit,
    cards_used,
    created_at,
    updated_at
from usage_quotas
where subscription_id = $1
  and period_start <= $2
  and period_end > $2
order by period_start desc
limit 1
`

type GetCurrentUsageQuotaBySubscriptionIDParams struct {
	SubscriptionID uuid.UUID
	NowAt          pgtype.Timestamptz
}

func (q *Queries) GetCurrentUsageQuotaBySubscriptionID(ctx context.Context, arg GetCurrentUsageQuotaBySubscriptionIDParams) (UsageQuota, error) {
	row := q.db.QueryRow(ctx, getCurrentUsageQuotaBySubscriptionID, arg.SubscriptionID, arg.NowAt)
	var i UsageQuota
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.CardsLimit,
		&i.CardsUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAddonProducts = `-- name: ListActiveAddonProducts :many
select
    id,
    code,
    title,
    description,
    price,
    cards_count,
    is_active,
    created_at,
    updated_at
from addon_products
where is_active = true
order by cards_count asc, created_at asc
`

func (q *Queries) ListActiveAddonProducts(ctx context.Context) ([]AddonProduct, error) {
	rows, err := q.db.Query(ctx, listActiveAddonProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AddonProduct
	for rows.Next() {
		var i AddonProduct
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.CardsCount,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveBillingPlans = `-- name: ListActiveBillingPlans :many
select
    id,
    code,
    name,
    monthly_price,
    yearly_monthly_price,
    cards_per_month,
    is_popular,
    is_active,
    created_at,
    updated_at
from plans
where is_active = true
order by monthly_price asc, created_at asc
`

func (q *Queries) ListActiveBillingPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listActiveBillingPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.MonthlyPrice,
			&i.YearlyMonthlyPrice,
			&i.CardsPerMonth,
			&i.IsPopular,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSubscriptionScheduledCancel = `-- name: MarkSubscriptionScheduledCancel :execrows
update subscriptions
set status = 'scheduled_cancel',
    cancels_at = $1,
    updated_at = now()
where id = $2
  and user_id = $3
  and status = 'active'
`

type MarkSubscriptionScheduledCancelParams struct {
	CancelsAt pgtype.Timestamptz
	ID        uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) MarkSubscriptionScheduledCancel(ctx context.Context, arg MarkSubscriptionScheduledCancelParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSubscriptionScheduledCancel, arg.CancelsAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sumReservedGenerationCardsForUserInPeriod = `-- name: SumReservedGenerationCardsForUserInPeriod :one
select coalesce(sum(card_count), 0)::bigint
from generations
where user_id = $1
  and status in ('queued', 'processing', 'completed')
  and created_at >= $2
  and created_at < $3
`

type SumReservedGenerationCardsForUserInPeriodParams struct {
	UserID      uuid.UUID
	PeriodStart pgtype.Timestamptz
	PeriodEnd   pgtype.Timestamptz
}

// Для проверки лимита учитываем уже созданные generation, которые ещё не завершились ошибкой.
// Так пользователь не сможет переполнить квоту пачкой параллельных запусков.
func (q *Queries) SumReservedGenerationCardsForUserInPeriod(ctx context.Context, arg SumReservedGenerationCardsForUserInPeriodParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumReservedGenerationCardsForUserInPeriod, arg.UserID, arg.PeriodStart, arg.PeriodEnd)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
