// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: blog.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPublishedBlogPosts = `-- name: CountPublishedBlogPosts :one
select count(*)::bigint
from blog_posts p
where p.status = 'published'
  and p.published_at is not null
  and p.published_at <= now()
`

// Считает статьи для серверной пагинации публичного списка.
func (q *Queries) CountPublishedBlogPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedBlogPosts)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countPublishedBlogPostsExcludingPost = `-- name: CountPublishedBlogPostsExcludingPost :one
select count(*)::bigint
from blog_posts p
where p.status = 'published'
  and p.published_at is not null
  and p.published_at <= now()
  and p.id <> $1
`

// Считает статьи списка без featured-материала, чтобы не дублировать его на первой странице.
func (q *Queries) CountPublishedBlogPostsExcludingPost(ctx context.Context, blogPostID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedBlogPostsExcludingPost, blogPostID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getFeaturedBlogPost = `-- name: GetFeaturedBlogPost :one
select
    p.id,
    p.slug,
    p.title,
    coalesce(p.excerpt, '') as excerpt,
    p.published_at,
    coalesce(m.reading_time_minutes, 1) as reading_time_minutes
from blog_posts p
left join blog_post_metrics m on m.blog_post_id = p.id
where p.status = 'published'
  and p.published_at is not null
  and p.published_at <= now()
order by p.published_at desc, p.created_at desc
limit 1
`

type GetFeaturedBlogPostRow struct {
	ID                 uuid.UUID
	Slug               string
	Title              string
	Excerpt            string
	PublishedAt        pgtype.Timestamptz
	ReadingTimeMinutes int32
}

// Возвращает последнюю опубликованную статью для hero-блока списка `/blog`.
func (q *Queries) GetFeaturedBlogPost(ctx context.Context) (GetFeaturedBlogPostRow, error) {
	row := q.db.QueryRow(ctx, getFeaturedBlogPost)
	var i GetFeaturedBlogPostRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.PublishedAt,
		&i.ReadingTimeMinutes,
	)
	return i, err
}

const getPublishedBlogPostBySlug = `-- name: GetPublishedBlogPostBySlug :one
select
    p.id,
    p.slug,
    p.title,
    coalesce(p.seo_description, '') as seo_description,
    coalesce(p.excerpt, '') as excerpt,
    p.published_at,
    p.updated_at,
    coalesce(m.reading_time_minutes, 1) as reading_time_minutes,
    coalesce(m.views_count, 0)::bigint as views_count
from blog_posts p
left join blog_post_metrics m on m.blog_post_id = p.id
where p.slug = $1
  and p.status = 'published'
  and p.published_at is not null
  and p.published_at <= now()
`

type GetPublishedBlogPostBySlugRow struct {
	ID                 uuid.UUID
	Slug               string
	Title              string
	SeoDescription     string
	Excerpt            string
	PublishedAt        pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	ReadingTimeMinutes int32
	ViewsCount         int64
}

// Возвращает опубликованную статью по slug вместе с SEO-данными и метриками.
func (q *Queries) GetPublishedBlogPostBySlug(ctx context.Context, slug string) (GetPublishedBlogPostBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPublishedBlogPostBySlug, slug)
	var i GetPublishedBlogPostBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.SeoDescription,
		&i.Excerpt,
		&i.PublishedAt,
		&i.UpdatedAt,
		&i.ReadingTimeMinutes,
		&i.ViewsCount,
	)
	return i, err
}

const listBlogCategories = `-- name: ListBlogCategories :many
select
    c.slug,
    c.label,
    count(*)::bigint as posts_count
from blog_categories c
join blog_post_categories pc on pc.blog_category_id = c.id
join blog_posts p on p.id = pc.blog_post_id
where p.status = 'published'
  and p.published_at is not null
  and p.published_at <= now()
group by c.id, c.slug, c.label
order by posts_count desc, c.label asc
`

type ListBlogCategoriesRow struct {
	Slug       string
	Label      string
	PostsCount int64
}

// Возвращает категории с количеством опубликованных статей в каждой из них.
func (q *Queries) ListBlogCategories(ctx context.Context) ([]ListBlogCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listBlogCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlogCategoriesRow
	for rows.Next() {
		var i ListBlogCategoriesRow
		if err := rows.Scan(&i.Slug, &i.Label, &i.PostsCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlogPostSections = `-- name: ListBlogPostSections :many
select
    id,
    blog_post_id,
    sort_order,
    kind,
    coalesce(title, '') as title,
    coalesce(level, 2) as level,
    payload,
    created_at,
    updated_at
from blog_post_sections
where blog_post_id = $1
order by sort_order asc, created_at asc
`

type ListBlogPostSectionsRow struct {
	ID         uuid.UUID
	BlogPostID uuid.UUID
	SortOrder  int32
	Kind       string
	Title      string
	Level      int32
	Payload    []byte
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

// Возвращает секции статьи в порядке, в котором их нужно рендерить на странице.
func (q *Queries) ListBlogPostSections(ctx context.Context, blogPostID uuid.UUID) ([]ListBlogPostSectionsRow, error) {
	rows, err := q.db.Query(ctx, listBlogPostSections, blogPostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlogPostSectionsRow
	for rows.Next() {
		var i ListBlogPostSectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.BlogPostID,
			&i.SortOrder,
			&i.Kind,
			&i.Title,
			&i.Level,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlogPostTags = `-- name: ListBlogPostTags :many
select
    t.slug,
    t.label
from blog_tags t
join blog_post_tags pt on pt.blog_tag_id = t.id
where pt.blog_post_id = $1
order by t.label asc
`

type ListBlogPostTagsRow struct {
	Slug  string
	Label string
}

// Возвращает теги статьи для шапки и SEO-блоков.
func (q *Queries) ListBlogPostTags(ctx context.Context, blogPostID uuid.UUID) ([]ListBlogPostTagsRow, error) {
	rows, err := q.db.Query(ctx, listBlogPostTags, blogPostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlogPostTagsRow
	for rows.Next() {
		var i ListBlogPostTagsRow
		if err := rows.Scan(&i.Slug, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlogTags = `-- name: ListBlogTags :many
select distinct
    t.slug,
    t.label
from blog_tags t
join blog_post_tags pt on pt.blog_tag_id = t.id
join blog_posts p on p.id = pt.blog_post_id
where p.status = 'published'
  and p.published_at is not null
  and p.published_at <= now()
order by t.label asc
`

type ListBlogTagsRow struct {
	Slug  string
	Label string
}

// Возвращает теги, которые используются в опубликованных статьях.
func (q *Queries) ListBlogTags(ctx context.Context) ([]ListBlogTagsRow, error) {
	rows, err := q.db.Query(ctx, listBlogTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlogTagsRow
	for rows.Next() {
		var i ListBlogTagsRow
		if err := rows.Scan(&i.Slug, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPopularBlogPosts = `-- name: ListPopularBlogPosts :many
select
    p.slug,
    p.title
from blog_posts p
left join blog_post_metrics m on m.blog_post_id = p.id
where p.status = 'published'
  and p.published_at is not null
  and p.published_at <= now()
order by coalesce(m.views_count, 0) desc, p.published_at desc, p.created_at desc
limit 5
`

type ListPopularBlogPostsRow struct {
	Slug  string
	Title string
}

// Возвращает популярные статьи для бокового блока.
func (q *Queries) ListPopularBlogPosts(ctx context.Context) ([]ListPopularBlogPostsRow, error) {
	rows, err := q.db.Query(ctx, listPopularBlogPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPopularBlogPostsRow
	for rows.Next() {
		var i ListPopularBlogPostsRow
		if err := rows.Scan(&i.Slug, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedBlogPosts = `-- name: ListPublishedBlogPosts :many
select
    p.id,
    p.slug,
    p.title,
    coalesce(p.excerpt, '') as excerpt,
    coalesce(c.label, '') as category_label,
    p.published_at,
    coalesce(m.reading_time_minutes, 1) as reading_time_minutes
from blog_posts p
left join blog_post_metrics m on m.blog_post_id = p.id
left join lateral (
    select bc.label
    from blog_post_categories pc
    join blog_categories bc on bc.id = pc.blog_category_id
    where pc.blog_post_id = p.id
    order by bc.label asc
    limit 1
) c on true
where p.status = 'published'
  and p.published_at is not null
  and p.published_at <= now()
order by p.published_at desc, p.created_at desc
limit $2
offset $1
`

type ListPublishedBlogPostsParams struct {
	OffsetRows int32
	LimitRows  int32
}

type ListPublishedBlogPostsRow struct {
	ID                 uuid.UUID
	Slug               string
	Title              string
	Excerpt            string
	CategoryLabel      string
	PublishedAt        pgtype.Timestamptz
	ReadingTimeMinutes int32
}

// Возвращает страницу опубликованных статей без дополнительных фильтров.
func (q *Queries) ListPublishedBlogPosts(ctx context.Context, arg ListPublishedBlogPostsParams) ([]ListPublishedBlogPostsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedBlogPosts, arg.OffsetRows, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedBlogPostsRow
	for rows.Next() {
		var i ListPublishedBlogPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.CategoryLabel,
			&i.PublishedAt,
			&i.ReadingTimeMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedBlogPostsExcludingPost = `-- name: ListPublishedBlogPostsExcludingPost :many
select
    p.id,
    p.slug,
    p.title,
    coalesce(p.excerpt, '') as excerpt,
    coalesce(c.label, '') as category_label,
    p.published_at,
    coalesce(m.reading_time_minutes, 1) as reading_time_minutes
from blog_posts p
left join blog_post_metrics m on m.blog_post_id = p.id
left join lateral (
    select bc.label
    from blog_post_categories pc
    join blog_categories bc on bc.id = pc.blog_category_id
    where pc.blog_post_id = p.id
    order by bc.label asc
    limit 1
) c on true
where p.status = 'published'
  and p.published_at is not null
  and p.published_at <= now()
  and p.id <> $1
order by p.published_at desc, p.created_at desc
limit $3
offset $2
`

type ListPublishedBlogPostsExcludingPostParams struct {
	BlogPostID uuid.UUID
	OffsetRows int32
	LimitRows  int32
}

type ListPublishedBlogPostsExcludingPostRow struct {
	ID                 uuid.UUID
	Slug               string
	Title              string
	Excerpt            string
	CategoryLabel      string
	PublishedAt        pgtype.Timestamptz
	ReadingTimeMinutes int32
}

// Возвращает страницу опубликованных статей без featured-материала, который уже показан в hero-блоке.
func (q *Queries) ListPublishedBlogPostsExcludingPost(ctx context.Context, arg ListPublishedBlogPostsExcludingPostParams) ([]ListPublishedBlogPostsExcludingPostRow, error) {
	rows, err := q.db.Query(ctx, listPublishedBlogPostsExcludingPost, arg.BlogPostID, arg.OffsetRows, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedBlogPostsExcludingPostRow
	for rows.Next() {
		var i ListPublishedBlogPostsExcludingPostRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.CategoryLabel,
			&i.PublishedAt,
			&i.ReadingTimeMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelatedBlogPostsByPostID = `-- name: ListRelatedBlogPostsByPostID :many
select
    p.slug,
    p.title
from blog_posts p
left join blog_post_categories pc
    on pc.blog_post_id = p.id
   and pc.blog_category_id in (
        select blog_category_id
        from blog_post_categories
        where blog_post_categories.blog_post_id = $1
   )
where p.id <> $1
  and p.status = 'published'
  and p.published_at is not null
  and p.published_at <= now()
group by p.id, p.slug, p.title, p.published_at, p.created_at
order by count(pc.blog_category_id) desc, p.published_at desc, p.created_at desc
limit 3
`

type ListRelatedBlogPostsByPostIDRow struct {
	Slug  string
	Title string
}

// Возвращает похожие статьи, сначала по общим категориям, затем по дате публикации.
func (q *Queries) ListRelatedBlogPostsByPostID(ctx context.Context, blogPostID uuid.UUID) ([]ListRelatedBlogPostsByPostIDRow, error) {
	rows, err := q.db.Query(ctx, listRelatedBlogPostsByPostID, blogPostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRelatedBlogPostsByPostIDRow
	for rows.Next() {
		var i ListRelatedBlogPostsByPostIDRow
		if err := rows.Scan(&i.Slug, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
