// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: generation.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateProjectByID = `-- name: ActivateProjectByID :execrows
update projects
set status = 'active',
    updated_at = now()
where id = $1
  and deleted_at is null
`

// После успешной генерации проект становится активным и начинает выглядеть как рабочий.
func (q *Queries) ActivateProjectByID(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, activateProjectByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addGenerationCardType = `-- name: AddGenerationCardType :exec
insert into generation_card_types (generation_id, position, card_type_id)
values ($1, $2, $3)
`

type AddGenerationCardTypeParams struct {
	GenerationID uuid.UUID
	Position     int32
	CardTypeID   string
}

func (q *Queries) AddGenerationCardType(ctx context.Context, arg AddGenerationCardTypeParams) error {
	_, err := q.db.Exec(ctx, addGenerationCardType, arg.GenerationID, arg.Position, arg.CardTypeID)
	return err
}

const clearGenerationArchiveAsset = `-- name: ClearGenerationArchiveAsset :exec
update generations
set archive_asset_id = null,
    updated_at = now()
where id = $1
`

func (q *Queries) ClearGenerationArchiveAsset(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearGenerationArchiveAsset, id)
	return err
}

const createAsset = `-- name: CreateAsset :one
insert into assets (id, user_id, kind, storage_key, original_filename, mime_type, size_bytes)
values ($1, $2, $3, $4, $5, $6, $7)
returning id, user_id, kind, storage_key, original_filename, mime_type, size_bytes, created_at
`

type CreateAssetParams struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Kind             string
	StorageKey       string
	OriginalFilename string
	MimeType         string
	SizeBytes        int64
}

// Создаёт запись о файле после того, как storage уже сохранил его по storage_key.
func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.StorageKey,
		arg.OriginalFilename,
		arg.MimeType,
		arg.SizeBytes,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.StorageKey,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const createGeneratedCard = `-- name: CreateGeneratedCard :one
insert into generated_cards (generation_id, asset_id, card_type_id, position)
values ($1, $2, $3, $4)
returning id, generation_id, asset_id, card_type_id, position, created_at
`

type CreateGeneratedCardParams struct {
	GenerationID uuid.UUID
	AssetID      uuid.UUID
	CardTypeID   string
	Position     int32
}

func (q *Queries) CreateGeneratedCard(ctx context.Context, arg CreateGeneratedCardParams) (GeneratedCard, error) {
	row := q.db.QueryRow(ctx, createGeneratedCard,
		arg.GenerationID,
		arg.AssetID,
		arg.CardTypeID,
		arg.Position,
	)
	var i GeneratedCard
	err := row.Scan(
		&i.ID,
		&i.GenerationID,
		&i.AssetID,
		&i.CardTypeID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createGeneration = `-- name: CreateGeneration :one
insert into generations (
    id,
    user_id,
    project_id,
    source_asset_id,
    marketplace_id,
    style_id,
    card_count,
    model_id,
    status,
    current_step,
    progress_percent
)
values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    'queued',
    'queued',
    0
)
returning id, user_id, project_id, source_asset_id, marketplace_id, style_id, card_count, status, current_step, progress_percent, error_message, archive_asset_id, started_at, finished_at, created_at, updated_at, model_id
`

type CreateGenerationParams struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ProjectID     uuid.UUID
	SourceAssetID uuid.UUID
	MarketplaceID string
	StyleID       string
	CardCount     int32
	ModelID       string
}

func (q *Queries) CreateGeneration(ctx context.Context, arg CreateGenerationParams) (Generation, error) {
	row := q.db.QueryRow(ctx, createGeneration,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
		arg.SourceAssetID,
		arg.MarketplaceID,
		arg.StyleID,
		arg.CardCount,
		arg.ModelID,
	)
	var i Generation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.SourceAssetID,
		&i.MarketplaceID,
		&i.StyleID,
		&i.CardCount,
		&i.Status,
		&i.CurrentStep,
		&i.ProgressPercent,
		&i.ErrorMessage,
		&i.ArchiveAssetID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelID,
	)
	return i, err
}

const deleteAssetByID = `-- name: DeleteAssetByID :execrows
delete from assets
where id = $1
`

func (q *Queries) DeleteAssetByID(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAssetByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGeneratedCardsByGenerationID = `-- name: DeleteGeneratedCardsByGenerationID :exec
delete from generated_cards
where generation_id = $1
`

func (q *Queries) DeleteGeneratedCardsByGenerationID(ctx context.Context, generationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGeneratedCardsByGenerationID, generationID)
	return err
}

const getAssetByID = `-- name: GetAssetByID :one
select id, user_id, kind, storage_key, original_filename, mime_type, size_bytes, created_at from assets
where id = $1
`

func (q *Queries) GetAssetByID(ctx context.Context, id uuid.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByID, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.StorageKey,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getGenerationByID = `-- name: GetGenerationByID :one
select id, user_id, project_id, source_asset_id, marketplace_id, style_id, card_count, status, current_step, progress_percent, error_message, archive_asset_id, started_at, finished_at, created_at, updated_at, model_id from generations
where id = $1
`

func (q *Queries) GetGenerationByID(ctx context.Context, id uuid.UUID) (Generation, error) {
	row := q.db.QueryRow(ctx, getGenerationByID, id)
	var i Generation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.SourceAssetID,
		&i.MarketplaceID,
		&i.StyleID,
		&i.CardCount,
		&i.Status,
		&i.CurrentStep,
		&i.ProgressPercent,
		&i.ErrorMessage,
		&i.ArchiveAssetID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelID,
	)
	return i, err
}

const getUserAssetByID = `-- name: GetUserAssetByID :one
select id, user_id, kind, storage_key, original_filename, mime_type, size_bytes, created_at from assets
where id = $1
  and user_id = $2
`

type GetUserAssetByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Позволяет клиенту использовать только свои загруженные исходники.
func (q *Queries) GetUserAssetByID(ctx context.Context, arg GetUserAssetByIDParams) (Asset, error) {
	row := q.db.QueryRow(ctx, getUserAssetByID, arg.ID, arg.UserID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.StorageKey,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getUserGenerationByID = `-- name: GetUserGenerationByID :one
select
    g.id, g.user_id, g.project_id, g.source_asset_id, g.marketplace_id, g.style_id, g.card_count, g.status, g.current_step, g.progress_percent, g.error_message, g.archive_asset_id, g.started_at, g.finished_at, g.created_at, g.updated_at, g.model_id,
    coalesce(archive.storage_key, '') as archive_storage_key
from generations g
left join assets archive on archive.id = g.archive_asset_id
where g.id = $1
  and g.user_id = $2
`

type GetUserGenerationByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetUserGenerationByIDRow struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	ProjectID         uuid.UUID
	SourceAssetID     uuid.UUID
	MarketplaceID     string
	StyleID           string
	CardCount         int32
	Status            string
	CurrentStep       string
	ProgressPercent   int32
	ErrorMessage      string
	ArchiveAssetID    pgtype.UUID
	StartedAt         pgtype.Timestamptz
	FinishedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	ModelID           string
	ArchiveStorageKey string
}

func (q *Queries) GetUserGenerationByID(ctx context.Context, arg GetUserGenerationByIDParams) (GetUserGenerationByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserGenerationByID, arg.ID, arg.UserID)
	var i GetUserGenerationByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.SourceAssetID,
		&i.MarketplaceID,
		&i.StyleID,
		&i.CardCount,
		&i.Status,
		&i.CurrentStep,
		&i.ProgressPercent,
		&i.ErrorMessage,
		&i.ArchiveAssetID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelID,
		&i.ArchiveStorageKey,
	)
	return i, err
}

const listGeneratedCardsByGenerationID = `-- name: ListGeneratedCardsByGenerationID :many
select
    gc.id,
    gc.card_type_id,
    gc.asset_id,
    a.storage_key
from generated_cards gc
join assets a on a.id = gc.asset_id
where gc.generation_id = $1
order by gc.position asc
`

type ListGeneratedCardsByGenerationIDRow struct {
	ID         uuid.UUID
	CardTypeID string
	AssetID    uuid.UUID
	StorageKey string
}

func (q *Queries) ListGeneratedCardsByGenerationID(ctx context.Context, generationID uuid.UUID) ([]ListGeneratedCardsByGenerationIDRow, error) {
	rows, err := q.db.Query(ctx, listGeneratedCardsByGenerationID, generationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGeneratedCardsByGenerationIDRow
	for rows.Next() {
		var i ListGeneratedCardsByGenerationIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CardTypeID,
			&i.AssetID,
			&i.StorageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenerationCardTypes = `-- name: ListGenerationCardTypes :many
select generation_id, position, card_type_id
from generation_card_types
where generation_id = $1
order by position asc
`

func (q *Queries) ListGenerationCardTypes(ctx context.Context, generationID uuid.UUID) ([]GenerationCardType, error) {
	rows, err := q.db.Query(ctx, listGenerationCardTypes, generationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GenerationCardType
	for rows.Next() {
		var i GenerationCardType
		if err := rows.Scan(&i.GenerationID, &i.Position, &i.CardTypeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGenerationCompleted = `-- name: MarkGenerationCompleted :exec
update generations
set status = 'completed',
    current_step = 'completed',
    progress_percent = 100,
    archive_asset_id = $1,
    updated_at = now(),
    finished_at = now()
where id = $2
`

type MarkGenerationCompletedParams struct {
	ArchiveAssetID pgtype.UUID
	ID             uuid.UUID
}

func (q *Queries) MarkGenerationCompleted(ctx context.Context, arg MarkGenerationCompletedParams) error {
	_, err := q.db.Exec(ctx, markGenerationCompleted, arg.ArchiveAssetID, arg.ID)
	return err
}

const markGenerationFailed = `-- name: MarkGenerationFailed :exec
update generations
set status = 'failed',
    current_step = 'failed',
    error_message = $1,
    updated_at = now(),
    finished_at = now()
where id = $2
`

type MarkGenerationFailedParams struct {
	ErrorMessage string
	ID           uuid.UUID
}

func (q *Queries) MarkGenerationFailed(ctx context.Context, arg MarkGenerationFailedParams) error {
	_, err := q.db.Exec(ctx, markGenerationFailed, arg.ErrorMessage, arg.ID)
	return err
}

const markGenerationProcessing = `-- name: MarkGenerationProcessing :execrows
update generations
set status = 'processing',
    current_step = $1,
    progress_percent = $2,
    error_message = '',
    started_at = coalesce(started_at, now()),
    updated_at = now()
where id = $3
  and status in ('queued', 'processing')
`

type MarkGenerationProcessingParams struct {
	CurrentStep     string
	ProgressPercent int32
	ID              uuid.UUID
}

// Первый worker-переход фиксирует старт обработки и защищает от повторного запуска завершённой задачи.
func (q *Queries) MarkGenerationProcessing(ctx context.Context, arg MarkGenerationProcessingParams) (int64, error) {
	result, err := q.db.Exec(ctx, markGenerationProcessing, arg.CurrentStep, arg.ProgressPercent, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateGenerationProgress = `-- name: UpdateGenerationProgress :execrows
update generations
set current_step = $1,
    progress_percent = $2,
    updated_at = now()
where id = $3
  and status = 'processing'
`

type UpdateGenerationProgressParams struct {
	CurrentStep     string
	ProgressPercent int32
	ID              uuid.UUID
}

func (q *Queries) UpdateGenerationProgress(ctx context.Context, arg UpdateGenerationProgressParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGenerationProgress, arg.CurrentStep, arg.ProgressPercent, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
