// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Одноразовые токены сброса пароля. Хранится только хэш, сырой токен уходит по email.
type PasswordResetToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

// Связь локального пользователя с внешним OAuth-провайдером.
type OauthAccount struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
	Email          pgtype.Text
	CreatedAt      pgtype.Timestamptz
}

// Сессии входа. В базе хранится только хэш токена.
type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

// Основной аккаунт пользователя. Не зависит от способа входа.
type User struct {
	ID              uuid.UUID
	Email           pgtype.Text
	PasswordHash    pgtype.Text
	Name            string
	EmailVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
