// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Разовые пакеты карточек для покупки сверх месячного лимита.
type AddonProduct struct {
	ID          uuid.UUID
	Code        string
	Title       string
	Description string
	Price       int32
	CardsCount  int32
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

// API-ключи пользовательских интеграций. Секрет хранится только в виде хэша.
type ApiKey struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	KeyHash     string
	MaskedValue string
	CreatedAt   pgtype.Timestamptz
	LastUsedAt  pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

// Файлы пользователя и артефакты генерации.
type Asset struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Kind             string
	StorageKey       string
	OriginalFilename string
	MimeType         string
	SizeBytes        int64
	CreatedAt        pgtype.Timestamptz
}

type BlogCategory struct {
	ID        uuid.UUID
	Slug      string
	Label     string
	CreatedAt pgtype.Timestamptz
}

// Статьи блога для SEO-страниц.
type BlogPost struct {
	ID             uuid.UUID
	Slug           string
	Title          string
	Excerpt        pgtype.Text
	SeoTitle       pgtype.Text
	SeoDescription pgtype.Text
	CoverAssetID   pgtype.UUID
	Status         string
	PublishedAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type BlogPostCategory struct {
	ID             uuid.UUID
	BlogPostID     uuid.UUID
	BlogCategoryID uuid.UUID
}

type BlogPostMetric struct {
	BlogPostID         uuid.UUID
	ViewsCount         int64
	ReadingTimeMinutes pgtype.Int4
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

// Универсальные секции статьи. Детали блока лежат в JSON payload.
type BlogPostSection struct {
	ID         uuid.UUID
	BlogPostID uuid.UUID
	SortOrder  int32
	Kind       string
	Title      pgtype.Text
	Level      pgtype.Int4
	Payload    []byte
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type BlogPostTag struct {
	ID         uuid.UUID
	BlogPostID uuid.UUID
	BlogTagID  uuid.UUID
}

type BlogTag struct {
	ID        uuid.UUID
	Slug      string
	Label     string
	CreatedAt pgtype.Timestamptz
}

// Готовые карточки, полученные после завершения генерации.
type GeneratedCard struct {
	ID           uuid.UUID
	GenerationID uuid.UUID
	AssetID      uuid.UUID
	CardTypeID   string
	Position     int32
	CreatedAt    pgtype.Timestamptz
}

// История запусков генерации карточек и прогресс фоновой задачи.
type Generation struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	ProjectID       uuid.UUID
	SourceAssetID   uuid.UUID
	MarketplaceID   string
	StyleID         string
	CardCount       int32
	Status          string
	CurrentStep     string
	ProgressPercent int32
	ErrorMessage    string
	ArchiveAssetID  pgtype.UUID
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ModelID         string
}

// Выбранные типы карточек внутри конкретного запуска генерации.
type GenerationCardType struct {
	GenerationID uuid.UUID
	Position     int32
	CardTypeID   string
}

// Пользовательские переключатели уведомлений.
type NotificationPreference struct {
	UserID        uuid.UUID
	PreferenceKey string
	Enabled       bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

// Связь локального пользователя с внешним OAuth-провайдером.
type OauthAccount struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
	Email          pgtype.Text
	CreatedAt      pgtype.Timestamptz
	// Снимок имени, которое вернул OAuth-провайдер во время входа.
	Name pgtype.Text
	// Снимок аватара, который вернул OAuth-провайдер во время входа.
	AvatarUrl pgtype.Text
	// Время последнего обновления снимка OAuth-аккаунта.
	UpdatedAt pgtype.Timestamptz
}

// Одноразовые токены сброса пароля. Хранится только хэш, сырой токен уходит по email.
type PasswordResetToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

// Платежи и checkout-сессии. Реальная интеграция провайдера сможет безопасно использовать эту таблицу позже.
type Payment struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	SubscriptionID    pgtype.UUID
	AddonProductID    pgtype.UUID
	Provider          string
	ProviderPaymentID pgtype.Text
	Kind              string
	Status            string
	Amount            int32
	Currency          string
	CheckoutUrl       pgtype.Text
	PaidAt            pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

// Неподтверждённые регистрации по email/паролю до ввода одноразового кода.
type PendingRegistration struct {
	ID           uuid.UUID
	Email        string
	Name         string
	PasswordHash string
	// Хэш одноразового кода из письма. Сырой код в базе не хранится.
	VerificationCodeHash  string
	VerificationExpiresAt pgtype.Timestamptz
	// Момент, раньше которого повторная отправка кода запрещена.
	ResendAvailableAt pgtype.Timestamptz
	// Количество неверных попыток ввода кода для текущего flow.
	AttemptCount int32
	// Количество уже отправленных кодов в рамках одного flow.
	ResendCount int32
	// Состояние flow: pending, verified, expired или blocked.
	Status           string
	LastEmailSentAt  pgtype.Timestamptz
	CreatedIpAddress string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	// Когда flow был завершён подтверждением или финально закрыт.
	CompletedAt pgtype.Timestamptz
}

// Тарифные планы, которые backend показывает на странице billing.
type Plan struct {
	ID                 uuid.UUID
	Code               string
	Name               string
	MonthlyPrice       int32
	YearlyMonthlyPrice pgtype.Int4
	CardsPerMonth      int32
	IsPopular          bool
	IsActive           bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

// Рабочий проект пользователя для генерации карточек маркетплейса.
type Project struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	Title              string
	Marketplace        string
	ProductName        string
	ProductDescription string
	Status             string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	// Момент мягкого удаления проекта. NULL означает, что проект активен.
	DeletedAt pgtype.Timestamptz
}

// Сессии входа. В базе хранится только хэш токена.
type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UserAgent string
	IpAddress string
}

// Текущее и прошлые состояния подписки пользователя по тарифу.
type Subscription struct {
	ID                     uuid.UUID
	UserID                 uuid.UUID
	PlanID                 uuid.UUID
	Status                 string
	Provider               string
	ProviderSubscriptionID pgtype.Text
	HasPaymentMethod       bool
	StartedAt              pgtype.Timestamptz
	CurrentPeriodStart     pgtype.Timestamptz
	CurrentPeriodEnd       pgtype.Timestamptz
	RenewsAt               pgtype.Timestamptz
	CancelsAt              pgtype.Timestamptz
	EndedAt                pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

// Снимок лимита на период подписки. cards_used пока хранится для будущей синхронизации.
type UsageQuota struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	SubscriptionID uuid.UUID
	PeriodStart    pgtype.Timestamptz
	PeriodEnd      pgtype.Timestamptz
	CardsLimit     int32
	CardsUsed      int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

// Основной аккаунт пользователя. Не зависит от способа входа.
type User struct {
	ID              uuid.UUID
	Email           pgtype.Text
	PasswordHash    pgtype.Text
	Name            string
	EmailVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// Расширенный профиль пользователя и дефолтные параметры генерации.
type UserSetting struct {
	UserID             uuid.UUID
	Phone              string
	Company            string
	DefaultMarketplace string
	CardsPerGeneration int32
	ImageFormat        string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	// Пользовательский аватар, загруженный через страницу настроек.
	AvatarAssetID pgtype.UUID
}
