// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// API-ключи пользовательских интеграций. Секрет хранится только в виде хэша.
type ApiKey struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	KeyHash     string
	MaskedValue string
	CreatedAt   pgtype.Timestamptz
	LastUsedAt  pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

// Пользовательские переключатели уведомлений.
type NotificationPreference struct {
	UserID        uuid.UUID
	PreferenceKey string
	Enabled       bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

// Связь локального пользователя с внешним OAuth-провайдером.
type OauthAccount struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
	Email          pgtype.Text
	CreatedAt      pgtype.Timestamptz
}

// Одноразовые токены сброса пароля. Хранится только хэш, сырой токен уходит по email.
type PasswordResetToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

// Рабочий проект пользователя для генерации карточек маркетплейса.
type Project struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	Title              string
	Marketplace        string
	ProductName        string
	ProductDescription string
	Status             string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	// Момент мягкого удаления проекта. NULL означает, что проект активен.
	DeletedAt pgtype.Timestamptz
}

// Сессии входа. В базе хранится только хэш токена.
type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UserAgent string
	IpAddress string
}

// Основной аккаунт пользователя. Не зависит от способа входа.
type User struct {
	ID              uuid.UUID
	Email           pgtype.Text
	PasswordHash    pgtype.Text
	Name            string
	EmailVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// Расширенный профиль пользователя и дефолтные параметры генерации.
type UserSetting struct {
	UserID             uuid.UUID
	Phone              string
	Company            string
	DefaultMarketplace string
	CardsPerGeneration int32
	ImageFormat        string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}
