// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: oauth_accounts.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthAccount = `-- name: CreateOAuthAccount :one
insert into oauth_accounts (
    user_id,
    provider,
    provider_user_id,
    email,
    name,
    avatar_url
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
) on conflict (provider, provider_user_id) do nothing
returning id, user_id, provider, provider_user_id, email, name, avatar_url, created_at, updated_at
`

type CreateOAuthAccountParams struct {
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
	Email          pgtype.Text
	Name           pgtype.Text
	AvatarUrl      pgtype.Text
}

type CreateOAuthAccountRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
	Email          pgtype.Text
	Name           pgtype.Text
	AvatarUrl      pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (CreateOAuthAccountRow, error) {
	row := q.db.QueryRow(ctx, createOAuthAccount,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
	)
	var i CreateOAuthAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestOAuthAvatarByUserID = `-- name: GetLatestOAuthAvatarByUserID :one
select coalesce(avatar_url, '') as avatar_url
from oauth_accounts
where user_id = $1
  and avatar_url is not null
  and avatar_url <> ''
order by updated_at desc, created_at desc
limit 1
`

// Берём свежий OAuth-аватар для /me. У обычной email-регистрации такого снимка может не быть.
func (q *Queries) GetLatestOAuthAvatarByUserID(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getLatestOAuthAvatarByUserID, userID)
	var avatar_url string
	err := row.Scan(&avatar_url)
	return avatar_url, err
}

const getOAuthAccountByProviderUserID = `-- name: GetOAuthAccountByProviderUserID :one
select
    id,
    user_id,
    provider,
    provider_user_id,
    email,
    name,
    avatar_url,
    created_at,
    updated_at
from oauth_accounts
where provider = $1
  and provider_user_id = $2
limit 1
`

type GetOAuthAccountByProviderUserIDParams struct {
	Provider       string
	ProviderUserID string
}

type GetOAuthAccountByProviderUserIDRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
	Email          pgtype.Text
	Name           pgtype.Text
	AvatarUrl      pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetOAuthAccountByProviderUserID(ctx context.Context, arg GetOAuthAccountByProviderUserIDParams) (GetOAuthAccountByProviderUserIDRow, error) {
	row := q.db.QueryRow(ctx, getOAuthAccountByProviderUserID, arg.Provider, arg.ProviderUserID)
	var i GetOAuthAccountByProviderUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthIdentityByProviderUserID = `-- name: GetOAuthIdentityByProviderUserID :one
select
    u.id,
    coalesce(u.email, '') as email,
    u.name,
    coalesce(oa.avatar_url, '') as avatar_url
from oauth_accounts oa
join users u on u.id = oa.user_id
where oa.provider = $1
  and oa.provider_user_id = $2
limit 1
`

type GetOAuthIdentityByProviderUserIDParams struct {
	Provider       string
	ProviderUserID string
}

type GetOAuthIdentityByProviderUserIDRow struct {
	ID        uuid.UUID
	Email     string
	Name      string
	AvatarUrl string
}

func (q *Queries) GetOAuthIdentityByProviderUserID(ctx context.Context, arg GetOAuthIdentityByProviderUserIDParams) (GetOAuthIdentityByProviderUserIDRow, error) {
	row := q.db.QueryRow(ctx, getOAuthIdentityByProviderUserID, arg.Provider, arg.ProviderUserID)
	var i GetOAuthIdentityByProviderUserIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
	)
	return i, err
}

const listOAuthAccountsByUserID = `-- name: ListOAuthAccountsByUserID :many
select
    id,
    provider,
    coalesce(email, '') as email,
    created_at
from oauth_accounts
where user_id = $1
order by created_at asc
`

type ListOAuthAccountsByUserIDRow struct {
	ID        uuid.UUID
	Provider  string
	Email     string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListOAuthAccountsByUserID(ctx context.Context, userID uuid.UUID) ([]ListOAuthAccountsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listOAuthAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOAuthAccountsByUserIDRow
	for rows.Next() {
		var i ListOAuthAccountsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOAuthAccountSnapshot = `-- name: UpdateOAuthAccountSnapshot :exec
update oauth_accounts
set email = coalesce($3, email),
    name = coalesce($4, name),
    avatar_url = coalesce($5, avatar_url),
    updated_at = now()
where provider = $1
  and provider_user_id = $2
`

type UpdateOAuthAccountSnapshotParams struct {
	Provider       string
	ProviderUserID string
	Email          pgtype.Text
	Name           pgtype.Text
	AvatarUrl      pgtype.Text
}

func (q *Queries) UpdateOAuthAccountSnapshot(ctx context.Context, arg UpdateOAuthAccountSnapshotParams) error {
	_, err := q.db.Exec(ctx, updateOAuthAccountSnapshot,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
	)
	return err
}
