// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: password_reset_tokens.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const invalidatePreviousPasswordResetTokens = `-- name: InvalidatePreviousPasswordResetTokens :exec
update password_reset_tokens
set used_at = now()
where user_id = $1
  and used_at is null
  and expires_at > now()
`

func (q *Queries) InvalidatePreviousPasswordResetTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, invalidatePreviousPasswordResetTokens, userID)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
insert into password_reset_tokens (
    user_id,
    token_hash,
    expires_at
) values (
    $1,
    $2,
    $3
)
returning id, user_id, expires_at, created_at
`

type CreatePasswordResetTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

type CreatePasswordResetTokenRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (CreatePasswordResetTokenRow, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i CreatePasswordResetTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getValidPasswordResetToken = `-- name: GetValidPasswordResetToken :one
select
    id,
    user_id
from password_reset_tokens
where token_hash = $1
  and used_at is null
  and expires_at > now()
limit 1
for update
`

type GetValidPasswordResetTokenRow struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetValidPasswordResetToken(ctx context.Context, tokenHash string) (GetValidPasswordResetTokenRow, error) {
	row := q.db.QueryRow(ctx, getValidPasswordResetToken, tokenHash)
	var i GetValidPasswordResetTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
	)
	return i, err
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :execrows
update password_reset_tokens
set used_at = now()
where token_hash = $1
  and used_at is null
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, markPasswordResetTokenUsed, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
