// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pending_registrations.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const blockPendingRegistration = `-- name: BlockPendingRegistration :execrows
update pending_registrations
set status = 'blocked',
    completed_at = now(),
    updated_at = now()
where id = $1
  and status = 'pending'
`

func (q *Queries) BlockPendingRegistration(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, blockPendingRegistration, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completePendingRegistration = `-- name: CompletePendingRegistration :execrows
update pending_registrations
set status = 'verified',
    completed_at = now(),
    updated_at = now()
where id = $1
  and status = 'pending'
`

func (q *Queries) CompletePendingRegistration(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, completePendingRegistration, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countRecentPendingRegistrationsByEmail = `-- name: CountRecentPendingRegistrationsByEmail :one
select count(*)
from pending_registrations
where email = $1
  and created_at >= $2
`

type CountRecentPendingRegistrationsByEmailParams struct {
	Email     string
	CreatedAt pgtype.Timestamptz
}

// Считаем недавние старты регистрации по email, чтобы ограничить перезапуск flow.
func (q *Queries) CountRecentPendingRegistrationsByEmail(ctx context.Context, arg CountRecentPendingRegistrationsByEmailParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentPendingRegistrationsByEmail, arg.Email, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentPendingRegistrationsByIP = `-- name: CountRecentPendingRegistrationsByIP :one
select count(*)
from pending_registrations
where created_ip_address = $1
  and created_at >= $2
`

type CountRecentPendingRegistrationsByIPParams struct {
	CreatedIpAddress string
	CreatedAt        pgtype.Timestamptz
}

// Считаем недавние старты регистрации по IP, чтобы не дать спамить новыми flow.
func (q *Queries) CountRecentPendingRegistrationsByIP(ctx context.Context, arg CountRecentPendingRegistrationsByIPParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentPendingRegistrationsByIP, arg.CreatedIpAddress, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPendingRegistration = `-- name: CreatePendingRegistration :one
insert into pending_registrations (
    email,
    name,
    password_hash,
    verification_code_hash,
    verification_expires_at,
    resend_available_at,
    attempt_count,
    resend_count,
    status,
    last_email_sent_at,
    created_ip_address
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    0,
    1,
    'pending',
    $7,
    $8
)
returning
    id,
    email,
    name,
    password_hash,
    verification_code_hash,
    verification_expires_at,
    resend_available_at,
    attempt_count,
    resend_count,
    status,
    last_email_sent_at,
    created_ip_address,
    created_at,
    updated_at,
    completed_at
`

type CreatePendingRegistrationParams struct {
	Email                 string
	Name                  string
	PasswordHash          string
	VerificationCodeHash  string
	VerificationExpiresAt pgtype.Timestamptz
	ResendAvailableAt     pgtype.Timestamptz
	LastEmailSentAt       pgtype.Timestamptz
	CreatedIpAddress      string
}

func (q *Queries) CreatePendingRegistration(ctx context.Context, arg CreatePendingRegistrationParams) (PendingRegistration, error) {
	row := q.db.QueryRow(ctx, createPendingRegistration,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.VerificationCodeHash,
		arg.VerificationExpiresAt,
		arg.ResendAvailableAt,
		arg.LastEmailSentAt,
		arg.CreatedIpAddress,
	)
	var i PendingRegistration
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.VerificationCodeHash,
		&i.VerificationExpiresAt,
		&i.ResendAvailableAt,
		&i.AttemptCount,
		&i.ResendCount,
		&i.Status,
		&i.LastEmailSentAt,
		&i.CreatedIpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const expirePendingRegistration = `-- name: ExpirePendingRegistration :execrows
update pending_registrations
set status = 'expired',
    completed_at = now(),
    updated_at = now()
where id = $1
  and status = 'pending'
`

func (q *Queries) ExpirePendingRegistration(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, expirePendingRegistration, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPendingRegistrationByEmail = `-- name: GetPendingRegistrationByEmail :one
select
    id,
    email,
    name,
    password_hash,
    verification_code_hash,
    verification_expires_at,
    resend_available_at,
    attempt_count,
    resend_count,
    status,
    last_email_sent_at,
    created_ip_address,
    created_at,
    updated_at,
    completed_at
from pending_registrations
where email = $1
limit 1
`

func (q *Queries) GetPendingRegistrationByEmail(ctx context.Context, email string) (PendingRegistration, error) {
	row := q.db.QueryRow(ctx, getPendingRegistrationByEmail, email)
	var i PendingRegistration
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.VerificationCodeHash,
		&i.VerificationExpiresAt,
		&i.ResendAvailableAt,
		&i.AttemptCount,
		&i.ResendCount,
		&i.Status,
		&i.LastEmailSentAt,
		&i.CreatedIpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getPendingRegistrationByEmailForUpdate = `-- name: GetPendingRegistrationByEmailForUpdate :one
select
    id,
    email,
    name,
    password_hash,
    verification_code_hash,
    verification_expires_at,
    resend_available_at,
    attempt_count,
    resend_count,
    status,
    last_email_sent_at,
    created_ip_address,
    created_at,
    updated_at,
    completed_at
from pending_registrations
where email = $1
limit 1
for update
`

// Блокируем flow по email, чтобы параллельные register-запросы не потеряли обновление имени или пароля.
func (q *Queries) GetPendingRegistrationByEmailForUpdate(ctx context.Context, email string) (PendingRegistration, error) {
	row := q.db.QueryRow(ctx, getPendingRegistrationByEmailForUpdate, email)
	var i PendingRegistration
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.VerificationCodeHash,
		&i.VerificationExpiresAt,
		&i.ResendAvailableAt,
		&i.AttemptCount,
		&i.ResendCount,
		&i.Status,
		&i.LastEmailSentAt,
		&i.CreatedIpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getPendingRegistrationForUpdate = `-- name: GetPendingRegistrationForUpdate :one
select
    id,
    email,
    name,
    password_hash,
    verification_code_hash,
    verification_expires_at,
    resend_available_at,
    attempt_count,
    resend_count,
    status,
    last_email_sent_at,
    created_ip_address,
    created_at,
    updated_at,
    completed_at
from pending_registrations
where id = $1
limit 1
for update
`

// FOR UPDATE нужен, чтобы verify и resend не меняли один flow одновременно.
func (q *Queries) GetPendingRegistrationForUpdate(ctx context.Context, id uuid.UUID) (PendingRegistration, error) {
	row := q.db.QueryRow(ctx, getPendingRegistrationForUpdate, id)
	var i PendingRegistration
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.VerificationCodeHash,
		&i.VerificationExpiresAt,
		&i.ResendAvailableAt,
		&i.AttemptCount,
		&i.ResendCount,
		&i.Status,
		&i.LastEmailSentAt,
		&i.CreatedIpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const incrementPendingRegistrationAttempt = `-- name: IncrementPendingRegistrationAttempt :one
update pending_registrations
set attempt_count = attempt_count + 1,
    updated_at = now()
where id = $1
returning attempt_count
`

// Возвращаем новое значение, чтобы сервис сразу понял, пора ли блокировать flow.
func (q *Queries) IncrementPendingRegistrationAttempt(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementPendingRegistrationAttempt, id)
	var attempt_count int32
	err := row.Scan(&attempt_count)
	return attempt_count, err
}

const refreshPendingRegistrationCode = `-- name: RefreshPendingRegistrationCode :one
update pending_registrations
set name = $2,
    password_hash = $3,
    verification_code_hash = $4,
    verification_expires_at = $5,
    resend_available_at = $6,
    resend_count = 1,
    attempt_count = 0,
    status = 'pending',
    last_email_sent_at = $7,
    created_ip_address = $8,
    updated_at = now(),
    completed_at = null
where id = $1
returning
    id,
    email,
    name,
    password_hash,
    verification_code_hash,
    verification_expires_at,
    resend_available_at,
    attempt_count,
    resend_count,
    status,
    last_email_sent_at,
    created_ip_address,
    created_at,
    updated_at,
    completed_at
`

type RefreshPendingRegistrationCodeParams struct {
	ID                    uuid.UUID
	Name                  string
	PasswordHash          string
	VerificationCodeHash  string
	VerificationExpiresAt pgtype.Timestamptz
	ResendAvailableAt     pgtype.Timestamptz
	LastEmailSentAt       pgtype.Timestamptz
	CreatedIpAddress      string
}

// Обновляем код и таймеры, не создавая новый flow для того же email.
func (q *Queries) RefreshPendingRegistrationCode(ctx context.Context, arg RefreshPendingRegistrationCodeParams) (PendingRegistration, error) {
	row := q.db.QueryRow(ctx, refreshPendingRegistrationCode,
		arg.ID,
		arg.Name,
		arg.PasswordHash,
		arg.VerificationCodeHash,
		arg.VerificationExpiresAt,
		arg.ResendAvailableAt,
		arg.LastEmailSentAt,
		arg.CreatedIpAddress,
	)
	var i PendingRegistration
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.VerificationCodeHash,
		&i.VerificationExpiresAt,
		&i.ResendAvailableAt,
		&i.AttemptCount,
		&i.ResendCount,
		&i.Status,
		&i.LastEmailSentAt,
		&i.CreatedIpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const resendPendingRegistrationCode = `-- name: ResendPendingRegistrationCode :one
update pending_registrations
set verification_code_hash = $2,
    verification_expires_at = $3,
    resend_available_at = $4,
    resend_count = $5,
    attempt_count = 0,
    last_email_sent_at = $6,
    status = 'pending',
    updated_at = now()
where id = $1
returning
    id,
    email,
    name,
    password_hash,
    verification_code_hash,
    verification_expires_at,
    resend_available_at,
    attempt_count,
    resend_count,
    status,
    last_email_sent_at,
    created_ip_address,
    created_at,
    updated_at,
    completed_at
`

type ResendPendingRegistrationCodeParams struct {
	ID                    uuid.UUID
	VerificationCodeHash  string
	VerificationExpiresAt pgtype.Timestamptz
	ResendAvailableAt     pgtype.Timestamptz
	ResendCount           int32
	LastEmailSentAt       pgtype.Timestamptz
}

// Повторная отправка всегда заменяет старый код новым и сбрасывает счётчик попыток.
func (q *Queries) ResendPendingRegistrationCode(ctx context.Context, arg ResendPendingRegistrationCodeParams) (PendingRegistration, error) {
	row := q.db.QueryRow(ctx, resendPendingRegistrationCode,
		arg.ID,
		arg.VerificationCodeHash,
		arg.VerificationExpiresAt,
		arg.ResendAvailableAt,
		arg.ResendCount,
		arg.LastEmailSentAt,
	)
	var i PendingRegistration
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.VerificationCodeHash,
		&i.VerificationExpiresAt,
		&i.ResendAvailableAt,
		&i.AttemptCount,
		&i.ResendCount,
		&i.Status,
		&i.LastEmailSentAt,
		&i.CreatedIpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updatePendingRegistrationProfile = `-- name: UpdatePendingRegistrationProfile :one
update pending_registrations
set name = $2,
    password_hash = $3,
    updated_at = now()
where id = $1
returning
    id,
    email,
    name,
    password_hash,
    verification_code_hash,
    verification_expires_at,
    resend_available_at,
    attempt_count,
    resend_count,
    status,
    last_email_sent_at,
    created_ip_address,
    created_at,
    updated_at,
    completed_at
`

type UpdatePendingRegistrationProfileParams struct {
	ID           uuid.UUID
	Name         string
	PasswordHash string
}

// Обновляем имя и пароль без выпуска нового кода, когда пользователь повторно отправил register до истечения flow.
func (q *Queries) UpdatePendingRegistrationProfile(ctx context.Context, arg UpdatePendingRegistrationProfileParams) (PendingRegistration, error) {
	row := q.db.QueryRow(ctx, updatePendingRegistrationProfile, arg.ID, arg.Name, arg.PasswordHash)
	var i PendingRegistration
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.VerificationCodeHash,
		&i.VerificationExpiresAt,
		&i.ResendAvailableAt,
		&i.AttemptCount,
		&i.ResendCount,
		&i.Status,
		&i.LastEmailSentAt,
		&i.CreatedIpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
