// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: projects.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
insert into projects (user_id, title, marketplace, product_name, product_description, status)
values ($1, $2, $3, $4, $5, 'draft')
returning id, user_id, title, marketplace, product_name, product_description, status, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	UserID             uuid.UUID
	Title              string
	Marketplace        string
	ProductName        string
	ProductDescription string
}

// Создаёт новый проект пользователя со статусом draft.
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.UserID,
		arg.Title,
		arg.Marketplace,
		arg.ProductName,
		arg.ProductDescription,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Marketplace,
		&i.ProductName,
		&i.ProductDescription,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
select id, user_id, title, marketplace, product_name, product_description, status, created_at, updated_at, deleted_at from projects
where id = $1
  and user_id = $2
  and deleted_at is null
`

type GetProjectByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Возвращает только активный проект его владельца.
// Мягко удалённые проекты снаружи считаются несуществующими.
func (q *Queries) GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, arg.ID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Marketplace,
		&i.ProductName,
		&i.ProductDescription,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCompletedCardsByProjectID = `-- name: ListCompletedCardsByProjectID :many
select
    gc.id,
    gc.card_type_id,
    gc.asset_id,
    a.storage_key
from generated_cards gc
join generations g on g.id = gc.generation_id
join projects p on p.id = g.project_id
join assets a on a.id = gc.asset_id
where g.project_id = $1
  and p.user_id = $2
  and p.deleted_at is null
  and g.status = 'completed'
order by g.finished_at desc nulls last, gc.position asc
`

type ListCompletedCardsByProjectIDParams struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
}

type ListCompletedCardsByProjectIDRow struct {
	ID         uuid.UUID
	CardTypeID string
	AssetID    uuid.UUID
	StorageKey string
}

// Возвращает все готовые карточки одного проекта владельца.
func (q *Queries) ListCompletedCardsByProjectID(ctx context.Context, arg ListCompletedCardsByProjectIDParams) ([]ListCompletedCardsByProjectIDRow, error) {
	rows, err := q.db.Query(ctx, listCompletedCardsByProjectID, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompletedCardsByProjectIDRow
	for rows.Next() {
		var i ListCompletedCardsByProjectIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CardTypeID,
			&i.AssetID,
			&i.StorageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedProjectCards = `-- name: ListCompletedProjectCards :many
select
    g.project_id,
    gc.id,
    gc.card_type_id,
    gc.asset_id,
    a.storage_key
from generated_cards gc
join generations g on g.id = gc.generation_id
join projects p on p.id = g.project_id
join assets a on a.id = gc.asset_id
where p.user_id = $1
  and p.deleted_at is null
  and g.status = 'completed'
order by g.finished_at desc nulls last, gc.position asc
`

type ListCompletedProjectCardsRow struct {
	ProjectID  uuid.UUID
	ID         uuid.UUID
	CardTypeID string
	AssetID    uuid.UUID
	StorageKey string
}

// Возвращает только готовые карточки по всем проектам пользователя.
// Дашборд и страница проекта не должны видеть queued/processing/failed.
func (q *Queries) ListCompletedProjectCards(ctx context.Context, userID uuid.UUID) ([]ListCompletedProjectCardsRow, error) {
	rows, err := q.db.Query(ctx, listCompletedProjectCards, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompletedProjectCardsRow
	for rows.Next() {
		var i ListCompletedProjectCardsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ID,
			&i.CardTypeID,
			&i.AssetID,
			&i.StorageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProjects = `-- name: ListUserProjects :many
select id, user_id, title, marketplace, product_name, product_description, status, created_at, updated_at, deleted_at from projects
where user_id = $1
  and deleted_at is null
order by updated_at desc
`

// Возвращает только активные проекты пользователя,
// отсортированные по дате последнего обновления.
func (q *Queries) ListUserProjects(ctx context.Context, userID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listUserProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Marketplace,
			&i.ProductName,
			&i.ProductDescription,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProject = `-- name: SoftDeleteProject :execrows
update projects
set status = 'archived',
    deleted_at = now(),
    updated_at = now()
where id = $1
  and user_id = $2
  and deleted_at is null
`

type SoftDeleteProjectParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Мягко удаляет проект: он исчезает из пользовательских списков,
// но остаётся в БД для истории, связей и будущих фоновых задач.
func (q *Queries) SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProject, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProject = `-- name: UpdateProject :one
update projects
set title               = $1,
    marketplace         = $2,
    product_name        = $3,
    product_description = $4,
    updated_at          = now()
where id = $5
  and user_id = $6
  and deleted_at is null
returning id, user_id, title, marketplace, product_name, product_description, status, created_at, updated_at, deleted_at
`

type UpdateProjectParams struct {
	Title              string
	Marketplace        string
	ProductName        string
	ProductDescription string
	ID                 uuid.UUID
	UserID             uuid.UUID
}

// Обновляет поля только у активного проекта.
// user_id в WHERE гарантирует, что чужой проект нельзя изменить.
func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Title,
		arg.Marketplace,
		arg.ProductName,
		arg.ProductDescription,
		arg.ID,
		arg.UserID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Marketplace,
		&i.ProductName,
		&i.ProductDescription,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
