// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: projects.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
insert into projects (user_id, title, marketplace, product_name, product_description, status)
values ($1, $2, $3, $4, $5, 'draft')
returning id, user_id, title, marketplace, product_name, product_description, status, created_at, updated_at
`

type CreateProjectParams struct {
	UserID             uuid.UUID
	Title              string
	Marketplace        string
	ProductName        string
	ProductDescription string
}

// Создаёт новый проект со статусом draft.
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.UserID,
		arg.Title,
		arg.Marketplace,
		arg.ProductName,
		arg.ProductDescription,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Marketplace,
		&i.ProductName,
		&i.ProductDescription,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :execrows
delete from projects where id = $1 and user_id = $2
`

type DeleteProjectParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Удаляет проект. Возвращает количество удалённых строк для проверки владения.
func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectByID = `-- name: GetProjectByID :one
select id, user_id, title, marketplace, product_name, product_description, status, created_at, updated_at from projects
where id = $1
  and user_id = $2
`

type GetProjectByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Возвращает проект только для его владельца.
func (q *Queries) GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, arg.ID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Marketplace,
		&i.ProductName,
		&i.ProductDescription,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserProjects = `-- name: ListUserProjects :many
select id, user_id, title, marketplace, product_name, product_description, status, created_at, updated_at from projects
where user_id = $1
order by updated_at desc
`

// Возвращает все проекты пользователя, отсортированные по дате обновления.
func (q *Queries) ListUserProjects(ctx context.Context, userID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listUserProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Marketplace,
			&i.ProductName,
			&i.ProductDescription,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
update projects
set title               = $1,
    marketplace         = $2,
    product_name        = $3,
    product_description = $4,
    updated_at          = now()
where id = $5 and user_id = $6
returning id, user_id, title, marketplace, product_name, product_description, status, created_at, updated_at
`

type UpdateProjectParams struct {
	Title              string
	Marketplace        string
	ProductName        string
	ProductDescription string
	ID                 uuid.UUID
	UserID             uuid.UUID
}

// Обновляет поля проекта. user_id в WHERE гарантирует, что чужой проект не изменить.
func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Title,
		arg.Marketplace,
		arg.ProductName,
		arg.ProductDescription,
		arg.ID,
		arg.UserID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Marketplace,
		&i.ProductName,
		&i.ProductDescription,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
