// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
insert into sessions (
    user_id,
    token_hash,
    expires_at
) values (
    $1,
    $2,
    $3
)
returning id, user_id, expires_at, created_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

type CreateSessionRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthIdentityByTokenHash = `-- name: GetAuthIdentityByTokenHash :one
select
    u.id,
    coalesce(u.email, '') as email,
    u.name,
    s.id as session_id,
    s.expires_at
from sessions s
join users u on u.id = s.user_id
where s.token_hash = $1
  and s.revoked_at is null
  and s.expires_at > now()
limit 1
`

type GetAuthIdentityByTokenHashRow struct {
	ID        uuid.UUID
	Email     string
	Name      string
	SessionID uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) GetAuthIdentityByTokenHash(ctx context.Context, tokenHash string) (GetAuthIdentityByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getAuthIdentityByTokenHash, tokenHash)
	var i GetAuthIdentityByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.SessionID,
		&i.ExpiresAt,
	)
	return i, err
}

const revokeSessionByTokenHash = `-- name: RevokeSessionByTokenHash :execrows
update sessions
set revoked_at = now()
where token_hash = $1
  and revoked_at is null
`

func (q *Queries) RevokeSessionByTokenHash(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionByTokenHash, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
