// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: settings.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
insert into api_keys (
    user_id,
    key_hash,
    masked_value
) values (
    $1,
    $2,
    $3
)
returning id, user_id, key_hash, masked_value, created_at, last_used_at, revoked_at
`

type CreateAPIKeyParams struct {
	UserID      uuid.UUID
	KeyHash     string
	MaskedValue string
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey, arg.UserID, arg.KeyHash, arg.MaskedValue)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.MaskedValue,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveAPIKeyByUserID = `-- name: GetActiveAPIKeyByUserID :one
select
    id,
    user_id,
    key_hash,
    masked_value,
    created_at,
    last_used_at,
    revoked_at
from api_keys
where user_id = $1
  and revoked_at is null
order by created_at desc
limit 1
`

func (q *Queries) GetActiveAPIKeyByUserID(ctx context.Context, userID uuid.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getActiveAPIKeyByUserID, userID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.MaskedValue,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserAvatarAssetByUserID = `-- name: GetUserAvatarAssetByUserID :one
select
    a.id,
    a.user_id,
    a.kind,
    a.storage_key,
    a.original_filename,
    a.mime_type,
    a.size_bytes,
    a.created_at
from user_settings us
join assets a on a.id = us.avatar_asset_id
where us.user_id = $1
limit 1
`

func (q *Queries) GetUserAvatarAssetByUserID(ctx context.Context, userID uuid.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getUserAvatarAssetByUserID, userID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.StorageKey,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getUserSettingsByUserID = `-- name: GetUserSettingsByUserID :one
select
    user_id,
    phone,
    company,
    avatar_asset_id,
    default_marketplace,
    cards_per_generation,
    image_format,
    created_at,
    updated_at
from user_settings
where user_id = $1
limit 1
`

type GetUserSettingsByUserIDRow struct {
	UserID             uuid.UUID
	Phone              string
	Company            string
	AvatarAssetID      pgtype.UUID
	DefaultMarketplace string
	CardsPerGeneration int32
	ImageFormat        string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) GetUserSettingsByUserID(ctx context.Context, userID uuid.UUID) (GetUserSettingsByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getUserSettingsByUserID, userID)
	var i GetUserSettingsByUserIDRow
	err := row.Scan(
		&i.UserID,
		&i.Phone,
		&i.Company,
		&i.AvatarAssetID,
		&i.DefaultMarketplace,
		&i.CardsPerGeneration,
		&i.ImageFormat,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotificationPreferencesByUserID = `-- name: ListNotificationPreferencesByUserID :many
select
    user_id,
    preference_key,
    enabled,
    created_at,
    updated_at
from notification_preferences
where user_id = $1
order by preference_key
`

func (q *Queries) ListNotificationPreferencesByUserID(ctx context.Context, userID uuid.UUID) ([]NotificationPreference, error) {
	rows, err := q.db.Query(ctx, listNotificationPreferencesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationPreference
	for rows.Next() {
		var i NotificationPreference
		if err := rows.Scan(
			&i.UserID,
			&i.PreferenceKey,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeActiveAPIKeysByUserID = `-- name: RevokeActiveAPIKeysByUserID :exec
update api_keys
set revoked_at = now()
where user_id = $1
  and revoked_at is null
`

func (q *Queries) RevokeActiveAPIKeysByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeActiveAPIKeysByUserID, userID)
	return err
}

const setUserAvatarAssetID = `-- name: SetUserAvatarAssetID :exec
insert into user_settings (
    user_id,
    avatar_asset_id
) values (
    $1,
    $2
)
on conflict (user_id) do update
set avatar_asset_id = excluded.avatar_asset_id,
    updated_at = now()
`

type SetUserAvatarAssetIDParams struct {
	UserID        uuid.UUID
	AvatarAssetID pgtype.UUID
}

func (q *Queries) SetUserAvatarAssetID(ctx context.Context, arg SetUserAvatarAssetIDParams) error {
	_, err := q.db.Exec(ctx, setUserAvatarAssetID, arg.UserID, arg.AvatarAssetID)
	return err
}

const upsertNotificationPreference = `-- name: UpsertNotificationPreference :one
insert into notification_preferences (
    user_id,
    preference_key,
    enabled
) values (
    $1,
    $2,
    $3
)
on conflict (user_id, preference_key) do update
set enabled = excluded.enabled,
    updated_at = now()
returning user_id, preference_key, enabled, created_at, updated_at
`

type UpsertNotificationPreferenceParams struct {
	UserID        uuid.UUID
	PreferenceKey string
	Enabled       bool
}

func (q *Queries) UpsertNotificationPreference(ctx context.Context, arg UpsertNotificationPreferenceParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPreference, arg.UserID, arg.PreferenceKey, arg.Enabled)
	var i NotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.PreferenceKey,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserSettings = `-- name: UpsertUserSettings :one
insert into user_settings (
    user_id,
    phone,
    company,
    avatar_asset_id,
    default_marketplace,
    cards_per_generation,
    image_format
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
on conflict (user_id) do update
set phone = excluded.phone,
    company = excluded.company,
    avatar_asset_id = excluded.avatar_asset_id,
    default_marketplace = excluded.default_marketplace,
    cards_per_generation = excluded.cards_per_generation,
    image_format = excluded.image_format,
    updated_at = now()
returning user_id, phone, company, avatar_asset_id, default_marketplace, cards_per_generation, image_format, created_at, updated_at
`

type UpsertUserSettingsParams struct {
	UserID             uuid.UUID
	Phone              string
	Company            string
	AvatarAssetID      pgtype.UUID
	DefaultMarketplace string
	CardsPerGeneration int32
	ImageFormat        string
}

type UpsertUserSettingsRow struct {
	UserID             uuid.UUID
	Phone              string
	Company            string
	AvatarAssetID      pgtype.UUID
	DefaultMarketplace string
	CardsPerGeneration int32
	ImageFormat        string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) UpsertUserSettings(ctx context.Context, arg UpsertUserSettingsParams) (UpsertUserSettingsRow, error) {
	row := q.db.QueryRow(ctx, upsertUserSettings,
		arg.UserID,
		arg.Phone,
		arg.Company,
		arg.AvatarAssetID,
		arg.DefaultMarketplace,
		arg.CardsPerGeneration,
		arg.ImageFormat,
	)
	var i UpsertUserSettingsRow
	err := row.Scan(
		&i.UserID,
		&i.Phone,
		&i.Company,
		&i.AvatarAssetID,
		&i.DefaultMarketplace,
		&i.CardsPerGeneration,
		&i.ImageFormat,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
