// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
insert into users (
    email,
    password_hash,
    name
) values (
    $1,
    $2,
    $3
)
returning id, coalesce(email, '') as email, name, created_at, updated_at
`

type CreateUserParams struct {
	Email        pgtype.Text
	PasswordHash pgtype.Text
	Name         string
}

type CreateUserRow struct {
	ID        uuid.UUID
	Email     string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Name)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVerifiedUser = `-- name: CreateVerifiedUser :one
insert into users (
    email,
    password_hash,
    name,
    email_verified_at
) values (
    $1,
    $2,
    $3,
    now()
)
returning id, coalesce(email, '') as email, name, created_at, updated_at
`

type CreateVerifiedUserParams struct {
	Email        pgtype.Text
	PasswordHash pgtype.Text
	Name         string
}

type CreateVerifiedUserRow struct {
	ID        uuid.UUID
	Email     string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateVerifiedUser(ctx context.Context, arg CreateVerifiedUserParams) (CreateVerifiedUserRow, error) {
	row := q.db.QueryRow(ctx, createVerifiedUser, arg.Email, arg.PasswordHash, arg.Name)
	var i CreateVerifiedUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserByID = `-- name: DeleteUserByID :execrows
delete from users
where id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAuthUserByEmail = `-- name: GetAuthUserByEmail :one
select
    id,
    coalesce(email, '') as email,
    name
from users
where email = $1
limit 1
`

type GetAuthUserByEmailRow struct {
	ID    uuid.UUID
	Email string
	Name  string
}

func (q *Queries) GetAuthUserByEmail(ctx context.Context, email pgtype.Text) (GetAuthUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getAuthUserByEmail, email)
	var i GetAuthUserByEmailRow
	err := row.Scan(&i.ID, &i.Email, &i.Name)
	return i, err
}

const getAuthUserByID = `-- name: GetAuthUserByID :one
select
    id,
    coalesce(email, '') as email,
    name
from users
where id = $1
limit 1
`

type GetAuthUserByIDRow struct {
	ID    uuid.UUID
	Email string
	Name  string
}

func (q *Queries) GetAuthUserByID(ctx context.Context, id uuid.UUID) (GetAuthUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getAuthUserByID, id)
	var i GetAuthUserByIDRow
	err := row.Scan(&i.ID, &i.Email, &i.Name)
	return i, err
}

const getLoginUserByEmail = `-- name: GetLoginUserByEmail :one
select
    id,
    email,
    name,
    coalesce(password_hash, '') as password_hash
from users
where email = $1
limit 1
`

type GetLoginUserByEmailRow struct {
	ID           uuid.UUID
	Email        pgtype.Text
	Name         string
	PasswordHash string
}

func (q *Queries) GetLoginUserByEmail(ctx context.Context, email pgtype.Text) (GetLoginUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getLoginUserByEmail, email)
	var i GetLoginUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
	)
	return i, err
}

const getUserCredentialsByID = `-- name: GetUserCredentialsByID :one
select
    id,
    coalesce(email, '') as email,
    name,
    coalesce(password_hash, '') as password_hash
from users
where id = $1
limit 1
`

type GetUserCredentialsByIDRow struct {
	ID           uuid.UUID
	Email        string
	Name         string
	PasswordHash string
}

func (q *Queries) GetUserCredentialsByID(ctx context.Context, id uuid.UUID) (GetUserCredentialsByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserCredentialsByID, id)
	var i GetUserCredentialsByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
update users
set password_hash = $2,
    updated_at = now()
where id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash pgtype.Text
}

// Обновляем хэш пароля пользователя. Возвращает количество затронутых строк —
// 0 означает, что пользователь не найден.
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
update users
set name = $2,
    email = $3,
    updated_at = now()
where id = $1
returning id, coalesce(email, '') as email, name, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID    uuid.UUID
	Name  string
	Email pgtype.Text
}

type UpdateUserProfileRow struct {
	ID        uuid.UUID
	Email     string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.Name, arg.Email)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
