// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
insert into users (
    email,
    password_hash,
    name
) values (
    $1,
    $2,
    $3
)
returning id, coalesce(email, '') as email, name, created_at, updated_at
`

type CreateUserParams struct {
	Email        pgtype.Text
	PasswordHash pgtype.Text
	Name         string
}

type CreateUserRow struct {
	ID        uuid.UUID
	Email     string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Name)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthUserByEmail = `-- name: GetAuthUserByEmail :one
select
    id,
    coalesce(email, '') as email,
    name
from users
where email = $1
limit 1
`

type GetAuthUserByEmailRow struct {
	ID    uuid.UUID
	Email string
	Name  string
}

func (q *Queries) GetAuthUserByEmail(ctx context.Context, email pgtype.Text) (GetAuthUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getAuthUserByEmail, email)
	var i GetAuthUserByEmailRow
	err := row.Scan(&i.ID, &i.Email, &i.Name)
	return i, err
}

const getAuthUserByID = `-- name: GetAuthUserByID :one
select
    id,
    coalesce(email, '') as email,
    name
from users
where id = $1
limit 1
`

type GetAuthUserByIDRow struct {
	ID    uuid.UUID
	Email string
	Name  string
}

func (q *Queries) GetAuthUserByID(ctx context.Context, id uuid.UUID) (GetAuthUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getAuthUserByID, id)
	var i GetAuthUserByIDRow
	err := row.Scan(&i.ID, &i.Email, &i.Name)
	return i, err
}

const getLoginUserByEmail = `-- name: GetLoginUserByEmail :one
select
    id,
    email,
    name,
    coalesce(password_hash, '') as password_hash
from users
where email = $1
limit 1
`

type GetLoginUserByEmailRow struct {
	ID           uuid.UUID
	Email        pgtype.Text
	Name         string
	PasswordHash string
}

func (q *Queries) GetLoginUserByEmail(ctx context.Context, email pgtype.Text) (GetLoginUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getLoginUserByEmail, email)
	var i GetLoginUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
	)
	return i, err
}
